- README.md
Add discussion about physics input parameters to readme
> Add physics params to readme

- spec/DocumentSpecification.md
Includes the initial draft of the specification for __Documents__.
> Document Specification Draft v0.0.0

- README.md
Length & width are current features
> Update readme physics inputs

- src/components/navbar/PathSelect.tsx
- src/document/DocumentModel.ts
This was a quick fix and small refactor
> Path select reflects active path and selects new path on creation

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/build.rs
- src-tauri/src/main.rs
- src/document/DocumentModel.ts
- Bindings to TrajoptLib added
- Still not passing drivetrain dynamics into TrajoptLib, needs to be added
- Disables "generate" button while generating
> Rust TrajoptLib backend integration

- .github/workflows/build.yml
- scripts/copy_trajoptlib_dylibs.cjs
- Previously, the build was actually just spitting out two Intel builds, this will actually make an arm64 dmg
> Actually build arm64 macos

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
> Upgrade TrajoptLib

- README.md
Add documentation on build process for each platform
> Build and Dev Server documentation

- src-tauri/src/main.rs
cleanup names and unneeded code in rust backend
> cleanup to main rs

- src-tauri/tauri.conf.in.json
> increase initial window size

- src-tauri/src/main.rs
> Disable terminal window on windows

- src/components/sidebar/PathSelector.tsx
> Fix name not updating in path selector

- src/components/input/Input.tsx
- src/components/sidebar/PathSelector.tsx
> Path name and number input commit on blur

- src/components/sidebar/PathSelector.tsx
> Fix path deletion confirm

- src/document/HolonomicPathStore.ts
not totally sold on the way i set this up yet, and even still could probably tune the heading weight a bit
> added rotation guess heuristic

- src/document/DocumentManager.ts
Refresh is still possible in devtools.
Closes #118
> Disable f5, ctrl-r, ctrl-shift-r and context menu

- src/document/DocumentManager.ts
> make traj file an object containing an array prop

- package.json
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/tauri.conf.in.json
Branch name is incorrect, version number is 2024.0.4
> Update version numbering to 2024.0.4 and include in title

- README.md
- choreolib/README.md
> Update to new docs

- src/components/config/WaypointConfigPanel.tsx
- src/components/field/svg/FieldOverlayRoot.tsx
- src/components/sidebar/PathSelector.tsx
- src/document/DocumentManager.ts
- src/document/UIStateStore.tsx
Also add default on/off to every view layer and standardizes on "samples" to describe control intervals.
> Add view layer with marks along trajectories at every control interval

- docs/estimating-moi.md
- mkdocs.yml
https://squidfunk.github.io/mkdocs-material/reference/math/#mathjax-mkdocsyml
> Add MathJax rendering to MkDocs

- src/document/DocumentManager.ts
> remove the ability to save to a non .chor filename

- src-tauri/src/main.rs
- src/document/DocumentManager.ts
> Old split traj files now delete when renaming paths

- docs/index.md
> Provide safety warnings and disclaim liability

- docs/js/mathjax.js
- docs/usage/estimating-moi.md
- mkdocs.yml
mkdocs has dedicated tags for making this look nicer. The main downside is GitHub preview no longer works.
> Fix "Estimating MOI" figures and captions

- .github/workflows/lint-format.yml
- docs/contributing/contributing-guide.md
- package.json
> Merge formatters into one npm script

- src/document/DocumentManager.ts
> [Feature] Add Zoom to Fit Waypoints Shortcut

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
> Upgrade TrajoptLib to squelch write failure exceptions

- index.html
- src/components/field/Field.tsx
- src/components/field/svg/FieldOverlayRoot.tsx
- src/document/DocumentManager.ts
- src/document/DocumentModel.tsx
zoomIn and zoomOut functionality with `control +` and `control -` for zooming into and out of the field.
Currently, zoomIn shortcut is not working yet.
> Add zoom-in and zoom-out functionality

- src/AppMenu.tsx
- src/Body.tsx
- src/components/field/Field.tsx
- src/components/field/PathAnimationPanel.tsx
- src/components/field/PathAnimationSlider.tsx
- src/components/field/svg/FieldAxisLines.tsx
- src/components/field/svg/FieldEventMarkerAddLayer.tsx
- src/components/field/svg/FieldEventMarkers.tsx
- src/components/field/svg/FieldGeneratedWaypoints.tsx
- src/components/field/svg/FieldGrid.tsx
- src/components/field/svg/FieldObstacles.tsx
- src/components/field/svg/FieldPathLines.tsx
- src/components/field/svg/FieldSamples.tsx
- src/components/field/svg/InterpolatedRobot.tsx
- src/components/field/svg/OverlayWaypoint.tsx
- src/components/navbar/Navbar.tsx
> Update React context declarations

- src/document/HolonomicPathStore.ts
Its done like this everywhere else dunno why it should be imported twice in different ways
> Standardise UUID import

- src/document/DocumentModel.tsx
- src/document/DocumentSpecTypes.ts
- src/document/HolonomicPathStore.ts
- src/document/previousSpecs/v0.3.1.json
- src/document/previousSpecs/v0_3_1.ts
Also fix logic for stale trajectory marker.
Related to #401, should fix the event markers being zeroed out since we no longer rely on isTrajectoryStale to deserialize them.
> Add new schema to save generated target of event marker

- src/document/DocumentModel.tsx
- src/document/HolonomicPathStore.ts
These issues also caused file corruption or trajectoryStale=false not being saved.
> Fix issues causing multiple autosaves on generation

- src/document/DocumentManager.ts
> Feature: Add Open File Shortcut

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/main.rs
- src/document/ConstraintStore.tsx
requires trajoptlib update before merging
> Max angular velocity constraint

- .github/workflows/choreolib.yml
- .github/workflows/docs.yml
This matches the development build of WPILib.
> Use Temurin JDK to build ChoreoLib

- choreolib/src/main/java/com/choreo/lib/ChoreoTrajectoryState.java
- choreolib/src/main/native/cpp/choreo/lib/ChoreoTrajectoryState.cpp
- choreolib/src/main/native/include/choreo/lib/ChoreoTrajectoryState.h
WPILib has better solutions for serialization at this point.
> Remove ChoreoTrajectoryState::AsArray()

- src/components/config/robotconfig/PathGradient.tsx
> Fix non-split case for split trajectories gradient

- .github/workflows/build.yml
https://github.com/SleipnirGroup/Choreo/actions/runs/9576671863/job/26403552159
See successful (draft) release run
> Fix artifact paths for cross-compiled mac artifacts

- trajoptlib/README.md
> Remove discord from Trajoptlib readme

- docs/usage/controls-shortcuts.md
> Update documentation for keyboard shortcuts

- trajoptlib/CMakeLists.txt
- trajoptlib/cmake/0001-Downgrade-to-C-20.patch
The C++20 patch also needed rebasing.
> Upgrade Sleipnir since MSVC flags changed slightly

- src-tauri/src/main.rs
- src/document/ConstraintStore.tsx
- src/document/HolonomicPathStore.ts
Added UI for the acceleration constraint and updated choreo initial guess control intervals based on acceleration. 
Fixes #421.
> [choreo] Add linear acceleration constraint to UI

- src/document/DocumentManager.ts
> Exclude project contents from LocalStorage when saving last opened file path

- .github/workflows/docs.yml
- choreolib/src/main/java/com/choreo/lib/ChoreoTrajectoryState.java
- choreolib/src/main/native/include/choreo/lib/ChoreoTrajectoryState.h
- make-docs.sh
- trajoptlib/include/trajopt/constraint/PointAtConstraint.hpp
- trajoptlib/include/trajopt/path/PathBuilder.hpp
> Fix C++ docs generation

- src-tauri/src/document/intervals.rs
- src/util/ObjectTyped.ts
- trajoptlib/src/SwerveTrajectoryGenerator.cpp
this is one of a few updates that should help with using non-square module layouts.
related to:
#549 
#587
> [choreo] Add anti tunneling to control interval guess

- src/document/DocumentManager.ts
- src/document/PathListStore.ts
> [choreo] Fix a couple of warnings from tsserver

- .github/workflows/trajoptlib-cpp.yml
runner.os isn't set properly on Windows.
> [ci] Replace runner.os with matrix.os

- .github/workflows/choreo.yml
- src-tauri/tauri.conf.json
> [ci] Build RPM package of Choreo

- src/document/ConstraintDefinitions.tsx
Choreo just didn't load otherwise
> Fix missing Units import

- trajoptlib/include/trajopt/SwerveTrajectoryGenerator.hpp
- trajoptlib/src/RustFFI.cpp
- trajoptlib/src/lib.rs
> Add lin/ang acceleration to SwerveTrajectorySample

- src/AppMenu.tsx
> Fix wording of "File" that should be "Project"

- src/components/field/svg/constraintDisplay/FieldConstraintAddLayer.tsx
> Fix constraint add blank screen on undo

- src-core/src/file_management/mod.rs
> Remove all traj writers on deploy root change

- Cargo.lock
- package.json
- src-cli/Cargo.toml
- src-core/Cargo.toml
- src-core/src/generation/generate.rs
- src-tauri/Cargo.toml
- src-tauri/build.rs
- src-tauri/src/built.rs
- src-tauri/src/main.rs
- src-tauri/src/tauri.rs
- src-tauri/tauri.conf.json
- src/util/BuildInfo.ts
- update_version.py
This can be used to close #598 and provide more data for debugging user issues
> [choreo] Add a way for frontend to get build info

- trajoptlib/include/trajopt/DifferentialTrajectoryGenerator.hpp
- trajoptlib/include/trajopt/SwerveTrajectoryGenerator.hpp
- trajoptlib/include/trajopt/util/GenerateLinearInitialGuess.hpp
- trajoptlib/src/DifferentialTrajectoryGenerator.cpp
I couldn't make this build without splitting the headers
> [trajoptlib] Use heading for tank

- src-core/src/generation/generate.rs
- src-core/src/generation/remote.rs
- src-core/src/generation/transformers/callback.rs
- src-core/src/spec/traj.rs
- src/document/2025/v2025_0_0.ts
- src/document/DocumentModel.tsx
This now matches the generator return format
> Change progress updates to send choreo-style samples

- .github/workflows/choreo.yml
- .github/workflows/choreolib.yml
This matches the value in src-tauri/tauri.conf.json.
> [ci] Set MACOS_DEPLOYMENT_TARGET macro to 13.3

- src/document/PathListStore.ts
> [choreo] Use new path name when duplicating

- src-core/src/generation/transformers/drivetrain_and_bumpers.rs
- src-core/src/spec/project.rs
- src/components/config/robotconfig/DimensionsConfigPanel.tsx
- src/document/2025/v2025_0_0.ts
- src/document/DocumentManager.ts
- src/document/RobotConfigStore.ts
> Diff track width config

- src/document/ExpressionStore.tsx
> Fix the lazy calculation of ExpressionStore

- .github/workflows/choreo.yml
- copy-sidecar.cjs
- src-tauri/tauri.conf.json
> Upload standalone binaries as artifacts

- src-core/src/generation/heading.rs
- src-core/src/spec/mod.rs
- src/components/config/ConstraintsConfigPanel.tsx
- src/components/config/variables/VariablesConfigPanel.tsx
- src/components/field/svg/FieldOverlayRoot.tsx
- src/components/field/svg/constraintDisplay/KeepInCircleOverlay.tsx
- src/components/field/svg/constraintDisplay/KeepInRectangleOverlay.tsx
- src/components/field/svg/constraintDisplay/KeepOutCircleOverlay.tsx
- src/components/field/svg/constraintDisplay/PointAtOverlay.tsx
- src/document/2025/DocumentTypes.ts
- src/document/2025/v2025_0_0.ts
- src/document/ConstraintDataStore.tsx
- src/document/ConstraintDefinitions.tsx
- src/document/EventMarkerStore.tsx
- src/document/ExpressionStore.tsx
- src/document/PathListStore.ts
- src/document/RobotConfigStore.ts
- src/document/path/ChoreoTrajStore.ts
- src/document/tauriCommands.ts
> Expr json object

- src/document/DocumentManager.ts
> [choreo] use finally in renamePath

- choreolib/build.gradle
- choreolib/config.gradle
- choreolib/src/main/java/choreo/trajectory/DifferentialSample.java
- choreolib/src/main/java/choreo/trajectory/SwerveSample.java
- choreolib/src/main/native/include/choreo/Choreo.h
- choreolib/src/main/native/include/choreo/trajectory/struct/DifferentialSampleStruct.h
- choreolib/src/main/native/include/choreo/trajectory/struct/SwerveSampleStruct.h
- choreolib/vendordeps/WPILibNewCommands.json
WPILib 2025 beta won't be coming out until mid-October, and some teams want to test Choreo before vendors get around to making beta releases.
> [choreolib] Downgrade to WPILib 2024

- trajoptlib/src/DifferentialTrajectoryGenerator.cpp
This matches the swerve kinematics closer.
Fixes #778.
> [trajoptlib] Remove redundant kinematic constraints

- .github/workflows/trajoptlib-cpp.yml
- .github/workflows/trajoptlib-sanitizers.yml
- trajoptlib/CMakePresets.json
Improves naming, and uses an inherit for examples + sccache
> [build] Fixup CMake presets a bit

- .github/workflows/trajoptlib-rust.yml
Helps https://github.com/SleipnirGroup/Choreo/issues/790
> [ci] Build TrajoptLib Rust in CI

- trajoptlib/src/DifferentialTrajectoryGenerator.cpp
- trajoptlib/src/SwerveTrajectoryGenerator.cpp
The wheel velocity constraints were incorrect. Only bound constraints were needed. The dynamics integration was also replaced with RK4 since the x, y, and heading dynamics are nonlinear.
> [trajoptlib] Use more compact differential drive model

- trajoptlib/include/trajopt/constraint/Constraint.hpp
- trajoptlib/include/trajopt/constraint/LaneConstraint.hpp
- trajoptlib/include/trajopt/constraint/PointLineRegionConstraint.hpp
- trajoptlib/include/trajopt/geometry/Translation2.hpp
- trajoptlib/src/RustFFI.cpp
- trajoptlib/src/RustFFI.hpp
Trajoptlib side of https://github.com/SleipnirGroup/Choreo/issues/580
TODO:
> [trajoptlib] Add lane constraint

- trajoptlib/include/trajopt/util/TrajoptUtil.hpp
input modulus incorrectly used a `+` where a `-` was needed
fixes #841
> [trajoptlib] fix inputModulus

- choreolib/src/main/native/include/choreo/trajectory/struct/DifferentialSampleStruct.h
- choreolib/src/main/native/include/choreo/trajectory/struct/SwerveSampleStruct.h
> [choreolib] Add "struct:" prefix to struct serialization

- src/components/config/ViewOptionsPanel.tsx
> Apply max height to variables panel.

- .github/workflows/choreo.yml
> [ci] Zip standalone executables

- choreolib/build.gradle
> [choreolib] Upgrade to GSON 2.11.0

- src-core/src/generation/heading.rs
fixes a bug where 0 angular velocity constraints on segments with only translation waypoints would not be adjusted correctly, sometimes causing the solver to generate a solution.
> [choreo] heading adjustment on 0 angular velocity segments of translation waypoints

- choreolib/src/main/java/choreo/auto/AutoFactory.java
- choreolib/src/main/java/choreo/auto/AutoRoutine.java
- choreolib/src/main/native/include/choreo/auto/AutoLoop.h
- docs/choreolib/auto-routines.md
Resolves https://github.com/SleipnirGroup/Choreo/issues/896
> [choreolib] Rename routine.enabled to routine.running

- choreolib/src/main/native/include/choreo/auto/AutoRoutine.h
> [choreolib] C++: Rename AutoLoop to AutoRoutine

- choreolib/src/main/java/choreo/auto/AutoTrajectory.java
- choreolib/src/main/java/choreo/trajectory/Trajectory.java
- choreolib/src/main/native/include/choreo/auto/AutoTrajectory.h
- choreolib/src/main/native/include/choreo/trajectory/Trajectory.h
- changed `atTimeAndPlace` to `atTimeAndPose`
- removed unused `timeOffset` member from `AutoTrajectory`
- inlined some methods only used once
- added easier flipping to trajectory sample fetching
- added method to get the underlying trajectory of an `AutoTrajectory`
> [choreolib] Cleaned up `AutoTrajectory` and `Trajectory` slightly

- choreolib/src/main/native/include/choreo/auto/AutoFactory.h
- choreolib/src/main/native/include/choreo/auto/AutoTrajectory.h
- choreolib/src/test/native/cpp/main.cpp
This also adds includes of Choreolib headers so we catch these in CI.
> [choreolib] Make C++ compile again

- .vscode/settings.json
- src-core/src/generation/transformers/drivetrain_and_bumpers.rs
- src-core/src/spec/mod.rs
- src-core/src/spec/project.rs
- src/components/config/robotconfig/ModuleConfigPanel.tsx
- src/document/2025/v2025_0_0.ts
- src/document/DocumentManager.ts
- src/document/RobotConfigStore.ts
- trajoptlib/examples/Differential/src/Main.cpp
- trajoptlib/examples/Swerve/src/Main.cpp
- trajoptlib/include/trajopt/DifferentialTrajectoryGenerator.hpp
- trajoptlib/include/trajopt/SwerveTrajectoryGenerator.hpp
- trajoptlib/src/DifferentialTrajectoryGenerator.cpp
- trajoptlib/src/RustFFI.cpp
- trajoptlib/src/SwerveTrajectoryGenerator.cpp
- trajoptlib/src/lib.rs
It doesn't appear to have a substantial impact of trajectories but it never urts to have.
> [trajoptlib] Add max friction force constraint

- choreolib/build.gradle
```
/__w/Choreo/Choreo/choreolib/src/main/java/choreo/trajectory/DifferentialSample.java:37: error: unmappable character (0xC2) for encoding US-ASCII
/** The acceleration of the left side in m/s??. */
^
```
> [choreolib] Fix Java encoding error

- choreolib/src/main/java/choreo/auto/AutoChooser.java
Resolves https://github.com/SleipnirGroup/Choreo/issues/928
> [choreolib] Fix AutoChooser display

- choreolib/src/main/java/choreo/trajectory/DifferentialSample.java
- choreolib/src/main/java/choreo/trajectory/SwerveSample.java
- choreolib/src/main/java/choreo/trajectory/Trajectory.java
- choreolib/src/main/java/choreo/trajectory/TrajectorySample.java
The user will handle this now, it could previously cause a runtime error.
> [choreolib-java] removed sample array from trajectory

- .styleguide
- choreolib/build.gradle
- choreolib/src/main/java/choreo/Choreo.java
- choreolib/src/main/java/choreo/auto/AutoFactory.java
- choreolib/src/main/native/include/choreo/Choreo.h
> [choreolib] Add usage reporting

- .github/workflows/trajoptlib-rust.yml
- trajoptlib/examples/Differential/src/Main.cpp
- trajoptlib/examples/Swerve/src/Main.cpp
- trajoptlib/examples/differential.rs
- trajoptlib/examples/swerve.rs
> [trajoptlib] Fix Rust example builds

- choreolib/src/main/native/include/choreo/Choreo.h
- choreolib/src/main/native/include/choreo/trajectory/DifferentialSample.h
- choreolib/src/main/native/include/choreo/trajectory/ProjectFile.h
- choreolib/src/main/native/include/choreo/trajectory/SwerveSample.h
- choreolib/src/main/native/include/choreo/trajectory/TrajectorySample.h
- choreolib/src/main/native/include/choreo/util/AllianceFlipperUtil.h
Also add missing includes.
Fixes #975.
> [choreolib] Remove AutoFactory reference from Choreo.h

- choreolib/src/main/java/choreo/auto/AutoTrajectory.java
Resolves https://github.com/SleipnirGroup/Choreo/issues/974
> [choreolib] Fix incorrect docs on AutoTrajectory.done()

- Cargo.lock
- package.json
- src-cli/Cargo.toml
- src-core/Cargo.toml
- src-tauri/Cargo.toml
- src-tauri/tauri.conf.json
Reverts SleipnirGroup/Choreo#983
> Revert "Bump version to v2025.0.0-beta-7"

- choreolib/src/main/java/choreo/Choreo.java
- choreolib/src/main/java/choreo/auto/AutoChooser.java
- choreolib/src/main/java/choreo/auto/AutoFactory.java
- choreolib/src/main/java/choreo/auto/AutoRoutine.java
- choreolib/src/main/java/choreo/auto/AutoTrajectory.java
Replaces DriverStation.reportWarning/reportError calls with wpilib's alerts api.
Fixes #996.
> [choreolib] Replace DriverStation.reportWarning/reportError with alerts

- src-core/src/file_management/formatter.rs
- src-core/src/file_management/mod.rs
Tested for .chor and .traj on a new project.
Reverts and properly implements https://github.com/SleipnirGroup/Choreo/commit/bff34f986233c17e80541acdb0a089e5848dd739
> Fix newline issue causing file overwrites

- choreolib/src/main/java/choreo/auto/AutoChooser.java
- choreolib/src/main/java/choreo/auto/AutoFactory.java
- choreolib/src/test/java/choreo/auto/AutoChooserTest.java
- docs/choreolib/auto-factory.md
- src-core/src/spec/trajectory.rs
It was easier to just convert the internals to use commands and drop the autofactory dependency on the factory entirely.
> [Choreolib-java] Updated auto chooser to not inject the factory

- docs/contributing/building-choreo.md
> [docs] Fix TrajoptLib link in tech stack

- choreolib/build.gradle
> [choreolib] Revert WPILib development build pin

- .github/workflows/choreolib.yml
Example of the outcome, before this workflow was restricted to tags: https://github.com/SleipnirGroup/ChoreoLib/pull/13
What the publishing workflow now skips if it's not a tag: https://github.com/SleipnirGroup/Choreo/actions/runs/12403982087/job/34628688962
> Automatic ChoreoLib Publishing

- trajoptlib/src/DifferentialTrajectoryGenerator.cpp
`SwerveTrajectoryGenerator::Generate(bool)` already does this.
> [trajoptlib] Reset differential cancellation flag

- trajoptlib/CMakeLists.txt
- trajoptlib/cmake/0001-Downgrade-to-C-20.patch
- trajoptlib/cmake/modules/CompilerFlags.cmake
Here's a diff:
```bash
git diff --stat -p 8bbce85252bc351c5aacb0de9f50fa31b8b9e1ae..5af8519f268a8075e245bb7cd411a81e1598f521 -- CMakeLists.txt cmake/ include/ src/
```
[sleipnir.patch.txt](https://github.com/user-attachments/files/18295192/sleipnir.patch.txt)
> [trajoptlib] Upgrade Sleipnir

- src/components/config/robotconfig/PathGradient.tsx
- src/components/field/svg/FieldGeneratedLines.tsx
* Clean up implementations and comment their steps better
* Make linear velocity and linear acceleration gradients properly support differential drive
* Update API documentation
> Refactor path gradients and make them properly support diff drive

- trajoptlib/include/trajopt/util/TrajoptUtil.hpp
- trajoptlib/src/DifferentialTrajectoryGenerator.cpp
- trajoptlib/src/SwerveTrajectoryGenerator.cpp
The arguments were backwards and didn't match the documentation.
> [trajoptlib] Clean up InputModulus()

- choreolib/src/main/java/choreo/trajectory/SwerveSample.java
> [choreolib] Fix SwerveSample docs typo

- choreolib/src/main/java/choreo/auto/AutoFactory.java
Void routine doesn't actually get run, so the trajectory command gets cancelled.
> Give AutoFactory.trajectoryCmd() an actual routine that runs

- src/document/ExpressionStore.tsx
Also adds lots of comments to the transformation logic.
> Fix bug preventing "pose.x" from being transformed

- src/components/config/robotconfig/PathGradient.tsx
- src/document/UIStateStore.tsx
Improves type safety on PathGradients
> Fix bad default path gradient

- trajoptlib/src/DifferentialTrajectoryGenerator.cpp
- trajoptlib/src/SwerveTrajectoryGenerator.cpp
This constraint is a hack, but it should stabilize the baseline relative to beta-9 while we work on an upcoming change to replace the constraint.
> [trajoptlib] Revert to anti-tunneling constraint

- trajoptlib/CMakeLists.txt
Sleipnir diff: https://github.com/SleipnirGroup/Sleipnir/compare/5af8519f268a8075e245bb7cd411a81e1598f521...e751c50947f4a960cb99c3b5138605f717d70274
> [trajoptlib] Upgrade Sleipnir for more detailed diagnostics

- src/components/config/variables/ExpressionsConfigPanel.tsx
- src/components/config/variables/PoseVariablesConfigPanel.tsx
- src/components/config/variables/VariablesConfigPanel.tsx
> [ui] Make the sections of the variables panel clearer

- trajoptlib/CMakeLists.txt
- trajoptlib/cmake/0001-Downgrade-to-C-20.patch
Sleipnir diff: https://github.com/SleipnirGroup/Sleipnir/compare/fb0c46d547cb7c7801cbbbb6bddd5d7f86061a8f...3b3df2fe485743ab73f395158d0225ad87d9e67c
> [trajoptlib] Upgrade Sleipnir for faster autodiff and less memory usage

- trajoptlib/CMakeLists.txt
- trajoptlib/cmake/0001-Downgrade-to-C-20.patch
Sleipnir diff: https://github.com/SleipnirGroup/Sleipnir/compare/3b3df2fe485743ab73f395158d0225ad87d9e67c...8c2cbe77e1ff319c825b9c908e4a31272c561b61
> [trajoptlib] Upgrade Sleipnir for more efficient sparsity logging

- choreolib/src/main/native/include/choreo/trajectory/Trajectory.h
> [choreolib] Fix compilation error in Trajectory::GetTotalTime()

- src-core/src/generation/intervals.rs
> [choreo] Fix generation failure for zero angular velocity constraint between pose and translation waypoints

- choreolib/src/main/native/include/choreo/trajectory/DifferentialSample.h
- choreolib/src/main/native/include/choreo/trajectory/SwerveSample.h
> [choreolib] Set default year for sample flip

- .github/workflows/choreo.yml
https://github.com/SleipnirGroup/Choreo/actions/runs/12913850447/job/36012930134#step:9:12 See the three original names here.
> Fix artifact names of aarch64 artifacts

- choreolib/src/main/java/choreo/auto/AutoFactory.java
> fix: param order in AutoFactory

- trajoptlib/include/trajopt/util/GenerateLinearInitialGuess.hpp
This matches C++23's std::vector::append_range().
> [trajoptlib] Rename append_vector() to append_range()

- README.md
> Update readme link to examples

- trajoptlib/src/DifferentialTrajectoryGenerator.cpp
- trajoptlib/src/SwerveTrajectoryGenerator.cpp
> [trajoptlib] Give each sample its own dt

- src-core/src/generation/transformers/mod.rs
- src-core/src/integration_tests/generate.rs
> Add logic to backend postprocess to update event marker timestamps

- .github/workflows/choreolib.yml
Should fix https://github.com/SleipnirGroup/Choreo/actions/runs/15916882802/job/44896057681.
> [SystemCore-alpha] Install SystemCore toolchain before running Gradle commands
