SleipnirGroup/Choreo

public/index.html

"A mathematically optimal trajectory generator for FRC"
Fixes the meta-description that shows on Discord embeds and elsewhere.

change site meta-description

---

spec/DocumentSpecification.md

Require at least two samples in a trajectory, and make it clear that arrays must contain only items of the type specified.

Modify trajectory requirements in specification

---

README.md

Since it appears that this no longer uses electron and instead uses Tauri (thank god, good idea!), this updates the readme heading to reflect that. May also be better to modify it to just say something along the lines of "How to run dev" or something, not sure.

Modified README.md to reflect usage of tauri instead of electron

---

src/document/DocumentManager.ts

Both `del` and `delete` fire on the delete keypress. This results in multiple deletions.
Closes #143

Remove redundant delete key binding

---

.github/workflows/build.yml
src-tauri/tauri.conf.in.json
vite.config.ts

`npm install` or at least `node scripts/generate_tauri_conf.cjs` will need to be run after pulling these changes, to recreate the tauri.conf.json.

Update tauri allowlist to match cargo.toml

---

src-tauri/tauri.conf.in.json

We don't actually need these changes outside of the saving overhaul branch, and they break linux ci somehow.

revert #165

---

src/document/DocumentModel.tsx

If the promise failed in the step before generation (the path validation), this would catch that failure and pass it as a success value as `rust_traj` and break a bunch of stuff. Users might not notice it but it makes a console error.

Remove redundant catch in generatePath

---

shell.nix

This adds a reproducible development environment with all the dependencies you need to build Choreo, plus the dynamic libraries added to `LD_LIBRARY_PATH` for convenience.
I originally hoped to fully build Choreo with Nix (rather than just a development shell to build it in), but I unfortunately wasn't able to get it working. It's particularly difficult because there are three different build systems involved (four counting Nix itself) and I wasn't able to get CMake to build trajoptlib without accessing the Internet sadly.

Add nix-shell development environment

---

src/components/input/Input.tsx

Entering and exiting an input element without changing the value will set the value to the last committed value, which might be for a different piece of data.
Steps to reproduce:
1. Create 2 waypoints. Select the first
2. Change its x coordinate and exit the input using Enter or clicking away. 
3. Select the other waypoint. 
4. Click into its x coordinate input and exit the input without changing anything.
5. The x coordinate of the second input will reset to the value of the the first

Fix bug regarding input exiting without changing

---

src-tauri/Cargo.toml
src-tauri/tauri.conf.in.json
src/components/config/WaypointConfigPanel.tsx
src/document/DocumentModel.tsx
src/document/HolonomicPathStore.ts
src/util/MathUtil.ts

Fix headings to wrap optimally before solver

---

src/components/field/PathAnimationPanel.tsx

MUI by default interprets a spacebar press as a click event on the focused element. This accessibility feature needs to be avoided, since we use spacebar for play/pause.

Block spacebar "repeat last button" MUI accessibility keybind

---

choreolib/src/main/java/com/choreo/lib/ChoreoTrajectoryState.java
choreolib/src/main/native/include/choreo/lib/ChoreoTrajectoryState.h

Taken directly from cad at https://cad.onshape.com/documents/dcbe49ce579f6342435bc298/w/b93673f5b2ec9c9bdcfec487/e/6ecb2d6b7590f4d1c820d5e3
Is there a possibility that because the link above is the optimized version the old number was gotten from the original import and thus this change is wrong?

Update Field Width Constant

---

docs/usage/controls-shortcuts.md

Closes #318 
From
```md
| Scroll Wheel, Trackpad G thesture | Zoom in or out of the map
```
To
```md
| Scroll Wheel, Trackpad Gesture | Zoom in or out of the map
```

Fix typo in Documentation

---

src/components/field/svg/FieldOverlayRoot.tsx
src/components/sidebar/PathSelector.tsx

zoomToFitWaypoints() ran on every rerender of the path selector, including start and end of every generation.

Remove extra console logs and distracting zoom-fit

---

.github/workflows/build.yml
src-tauri/tauri.conf.json

Add AppImage build

---

choreolib/src/main/java/com/choreo/lib/ChoreoTrajectory.java
choreolib/src/main/native/cpp/choreo/lib/ChoreoTrajectory.cpp
choreolib/src/main/native/include/choreo/lib/ChoreoTrajectory.h

Addresses #390 and adds getters for the flipped initial and final poses.

Add getFlippedInitialPose() and getFlippedFinalPose() to ChoreoTrajectory

---

src/document/EventMarkerStore.tsx

Affects file opening and path duplication (since duplication serializes and deserializes a path into a copy).
This works by allowing `undefined` as a marker target on marker creation.
Known issue/potential unwanted behavior: Once the marker is retargeted on the duplicate, its **!** message will say "marker added since last generation!" if the previous trajectory was stale when duplicated.

Allow markers with missing targets to be deserialized

---

.github/workflows/build.yml

See the path used here: https://github.com/SleipnirGroup/Choreo/actions/runs/8427814991/job/23079514897#step:3:44
and how the CI subsequently fails by using the wrong working directory for renaming the aarch64 installer.

Change artifact path of aarch64 windows installer

---

docs/contributing/building-choreo.md

I found the minimum Rust version via `cargo msrv`.

Add Git and version numbers to build requirements

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/main.rs
src/document/ConstraintStore.tsx

#381
along with https://github.com/SleipnirGroup/TrajoptLib/pull/140

Add PointAt constraint

---

src/components/config/ViewOptionsPanel.tsx
src/components/config/WaypointConfigPanel.module.css
src/components/field/Field.tsx
src/document/UIStateStore.tsx

I checked myself, but make sure I didn't miss anything with the refactor, since there is css, js, and html that needs to change. I tested it, though, and it visually works with no devtool errors.

Codebase: Refactor from VisibilityPanel to ViewOptionsPanel

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
src/components/config/KeyboardShortcutsPanel.tsx
src/components/config/SettingsModal.tsx
src/document/DocumentManager.ts
src/document/UIStateStore.tsx

Closes #373
Ctrl/Command key is shown depending on the user's detected OS

Add list of keyboard shortcuts to document settings

---

src/document/HolonomicPathStore.ts

i <= endIdx would apply the velocity constraint to the segment after the endIdx waypoint, which not intended

Don't apply max velocity constraint to end point

---

choreolib/src/main/java/com/choreo/lib/ChoreoTrajectoryState.java
choreolib/src/main/native/include/choreo/lib/ChoreoTrajectoryState.h

Fix ChoreoTrajectoryState constructor docs typo

---

src/AppMenu.tsx

Before: The button positions depend on the length of the directory path and wrap awkwardly.
After: The button positions are fixed and not dependent on the filepath.

Move copy and open directory buttons in menu to stable position.

---

src/components/field/Field.tsx
src/components/field/svg/FieldOverlayRoot.tsx
src/document/CircularObstacleStore.tsx
src/document/ConstraintStore.tsx
src/document/EventMarkerStore.tsx
src/document/HolonomicWaypointStore.ts

Other uses of selectedSidebarItem were guarded behind undefined-checks already. Note that `safeGetIdentifier` returns `undefined` if the input is `undefined`, so the equality checks were made triple-equals for better comparison safety.

Improve handling of sidebar and navbar selection being undefined/-1

---

.github/workflows/build.yml
.github/workflows/choreolib.yml

macOS 12 will hit EOL later this year.

Update macOS deployment target to 13

---

src/components/field/svg/constraintDisplay/FieldConstraintAddLayer.tsx

stop points (and future waypoint-only constraints) should only be added to a single waypoint. this adjusts the constraint adding UI so that adding a stop point is completed after clicking a single waypoint.

[choreo] short circuit add constraint layer for constraints with only waypoint scopes

---

.github/workflows/choreo.yml

Tauri always puts the installer in the same location everytime. Removing the wildcard means the zip file can contain just the installer with no extra directories.

[ci] Shorten recursive wildcard

---

.github/workflows/choreo.yml

[Since path hierarchies are preserved after the first wildcard](https://github.com/actions/upload-artifact/?tab=readme-ov-file#upload-using-multiple-paths-and-exclusions), the paths to the installer files have been hardcoded, leaving only the installer file name as a wildcard.

[ci] Hardcode all paths to installers

---

trajoptlib/src/DifferentialTrajectoryGenerator.cpp

Resolves https://github.com/SleipnirGroup/Choreo/issues/621
Basically a copy paste of https://github.com/SleipnirGroup/Choreo/pull/618 but with max angular velocity found using 2 * maxDrivetrainVelocity / trackwidth cause with vR and vL at max magnitude in opposite direction your essentially doing 2 vR (assuming equal max magnitude which we already assume). 
This doesn't appear to create any regressions (the same example fails)

[trajoptlib] Set better initial value of dt_sgmt variable for tank

---

.github/workflows/trajoptlib-cpp.yml
trajoptlib/CMakeLists.txt
trajoptlib/test/src/geometry/Translation2dTest.cpp

Adds Sleipnir's build directory to the DLL search paths. [The Catch2 feature](https://github.com/catchorg/Catch2/blob/devel/extras/Catch.cmake#L120) that enabled this fix requires CMake >=3.22 though. I also modified one of tests that was failing on my system.
Fixes #512.

[ci] Fix TrajoptLib tests failing on Windows

---

.github/workflows/cache-cleanup.yml

`pull_request` doesn't have the necessary perms, so `pull_request_target` is used instead.

[ci] Use pull_request_target event for deleting caches

---

.github/workflows/cache-cleanup.yml

Uses `gh cache` which means caches with a hyphen can be deleted
Removes repo checkout
Removes workflow_dispatch trigger

[ci] Improve PR cache remover

---

src/AppMenu.tsx

Since the Save Project button now exports all trajectories, the button is no longer needed. Some of the old file terms were also switched to use project and an old trajectory method was removed.

[choreo] Remove redundant export all trajectories button

---

package.json
pnpm-lock.yaml
src/document/DocumentManager.ts
src/document/PathListStore.ts

ajv stopped being used in #672, uuid was replaced with a built-in, and `@typescript-eslint/parser` is a dev dependency, not an app dependency.

Clean up npm dependencies

---

Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/tauri.rs

Tauri v2's log location getter now requires an app handle, which isn't available by the time setup_tracing() is called. Instead, this PR just uses the dirs package.

[choreo] Move logs to dirs::state_dir

---

src-core/src/generation/heading.rs

-fixes an indexing bug where a zero angular velocity constraint on wpts 3-4 would incorrectly report a heading conflict with a pose on wpt 5.
-adjusts translation and guess waypoint headings that are a part of zero angular velocity segments based on surrounding pose and point at constraints

[choreo] Add better heading adjustment for zero angular velocity segments

---

src/document/DocumentManager.ts

new projects were created with a single path called "NewPath", and the add path button was using "New Path" (with space).

[choreo] update default new project path name to match add path

---

src/document/DocumentManager.ts

allows paths without .traj files to be deleted without needing an app restart or to generate a .traj file
needs someone who knows the frontend JS/ts to OK this.
fixes #725

[choreo] use finally instead of then

---

src/components/field/svg/FieldEventMarkerAddLayer.tsx
src/components/sidebar/PathSelector.tsx
src/document/DocumentModel.tsx
src/document/path/HolonomicPathStore.ts

Path Config panel is temporarily disabled, but other path-wide configs could go there.
Stale indicator will be replaced with comparison against snapshot
usesDefaultObstacles was never used in logic.

Removes stale indicator, path-wide detail settings, usesDefaultObstacles

---

src-core/src/generation/transformers/drivetrain_and_bumpers.rs
trajoptlib/examples/differential.rs
trajoptlib/examples/swerve.rs
trajoptlib/include/trajopt/path/PathBuilder.hpp
trajoptlib/src/RustFFI.cpp
trajoptlib/src/RustFFI.hpp
trajoptlib/src/lib.rs

Closes #788 
No spec breakage.

Add rust ffi asymmetric bumper support #788

---

src/document/DocumentModel.tsx

The exception thrown in the `finally` block absorbed the one from the generator.

Fix "unlisten is not a function" issue

---

trajoptlib/include/trajopt/util/GenerateLinearInitialGuess.hpp
trajoptlib/include/trajopt/util/TrajoptUtil.hpp
trajoptlib/src/DifferentialTrajectoryGenerator.cpp
trajoptlib/src/SwerveTrajectoryGenerator.cpp
trajoptlib/test/src/util/TrajoptUtilTest.cpp

GetIndex() previously had an increment on all calls to it. It also had inconsistent usage where uses assumed both 0 and 1 based indexing. This PR changes the function to be 0 indexed on waypoints and samples within segments.
the relevant code in swerve and differential drive generators have been updated.

[trajoptlib] Make GetIndex() usage consistent and fix GetIndex()

---

trajoptlib/include/trajopt/DifferentialTrajectoryGenerator.hpp
trajoptlib/include/trajopt/SwerveTrajectoryGenerator.hpp
trajoptlib/include/trajopt/util/TrajoptUtil.hpp
trajoptlib/src/DifferentialTrajectoryGenerator.cpp
trajoptlib/src/SwerveTrajectoryGenerator.cpp

[trajoptlib] Make constraints use current and next index

---

src-core/src/generation/heading.rs

This was indexing the waypoints array without guesses removed, but using the fixScope adjusted constraints.

Remove bad scope-fixing in heading conflict checks

---

src-tauri/src/logging.rs
trajoptlib/examples/differential.rs

We aren't no-std so we should be using the std namespace

Use std instead of core

---

src-core/src/generation/transformers/callback.rs
src-core/src/generation/transformers/constraints.rs
src-core/src/generation/transformers/drivetrain_and_bumpers.rs
src-core/src/generation/transformers/interval_count.rs
src-core/src/generation/transformers/mod.rs
trajoptlib/examples/Differential/src/Main.cpp
trajoptlib/examples/Swerve/src/Main.cpp
trajoptlib/examples/differential.rs
trajoptlib/examples/swerve.rs
trajoptlib/include/trajopt/path/PathBuilder.hpp
trajoptlib/src/RustFFI.cpp
trajoptlib/src/RustFFI.hpp
trajoptlib/src/lib.rs
trajoptlib/test/src/DifferentialPathBuilderTest.cpp
trajoptlib/test/src/SwervePathBuilderTest.cpp

The Rust *PathBuilder classes were renamed to *TrajectoryGenerator to better reflect what they're used for.

Sort C++ PathBuilder functions and remove PathBuilder Rust trait

---

choreolib/src/main/native/include/choreo/auto/AutoFactory.h
choreolib/src/main/native/include/choreo/auto/AutoTrajectory.h

The enclosing choreo namespace makes it redundant.

[choreolib] Remove Choreo prefix from typedef

---

choreolib/src/main/java/choreo/Choreo.java
choreolib/src/main/java/choreo/auto/AutoFactory.java
choreolib/src/main/java/choreo/auto/AutoTrajectory.java
choreolib/src/main/native/include/choreo/auto/AutoFactory.h
choreolib/src/main/native/include/choreo/auto/AutoTrajectory.h

Users need to know the typedef is a BiConsumer anyway to pass the correct kind of function to it, so the typedef just makes it harder to learn how to use classes that take a controller function.

[choreolib] Remove controller function typedef

---

choreolib/py/choreo/__init__.py
choreolib/py/choreo/test/choreolib_test.py
choreolib/py/choreo/test/resources/swerve_test.traj
choreolib/src/main/java/choreo/trajectory/EventMarker.java
choreolib/src/main/native/cpp/choreo/trajectory/EventMarker.cpp
choreolib/src/test/java/choreo/ChoreoTests.java
choreolib/src/test/native/cpp/TrajectoryFileTests.cpp
src-core/src/spec/trajectory.rs
src/components/config/eventmarker/CommandDraggable.tsx
src/components/config/eventmarker/EventMarkerConfigPanel.tsx
src/components/field/PathAnimationSlider.tsx
src/components/field/svg/FieldEventMarkerAddLayer.tsx
src/components/field/svg/FieldEventMarkers.tsx
src/components/sidebar/SidebarEventMarker.tsx
src/document/2025/v2025_0_0.ts
src/document/CommandStore.tsx
src/document/DocumentManager.ts
src/document/DocumentModel.tsx
src/document/EventMarkerStore.tsx
src/document/path/HolonomicPathStore.ts

New Spec:
All markers in the `events` property of .traj root
```js
{
name: "used for triggers",
from: {
offset: Expression
targetTimestamp: number // offset.val + targetTimestamp = marker timestamp
target: WaypointIDX // ignored by libraries
},
to: { // same as from, reserved for later},
event: {/*pplib command with waitTime an Expression*/} | null //markers can have no gui-attached command.
}
```

Use marker name for triggers; change spec to prepare for timestamp-range markers.

---

choreolib/py/choreo/__init__.py
choreolib/py/choreo/test/choreolib_test.py
choreolib/src/main/java/choreo/Choreo.java
choreolib/src/main/native/cpp/choreo/trajectory/Trajectory.cpp
choreolib/src/test/java/choreo/ChoreoTests.java
choreolib/src/test/native/cpp/TrajectoryFileTests.cpp
src-core/src/generation/transformers/mod.rs
src-core/src/spec/trajectory.rs

* On generation, the split array will now hold 0 always, in addition to any other split indices. 
* Libraries have been updated to add the 0 in if it doesn't exist.

Make sure trajectories have at least one split section

---

src/document/DocumentManager.ts

This was fully reimplemented, but disabled, probably as an artifact of a debugging session.

Re-enable opening of last project

---

choreolib/src/main/native/include/choreo/auto/AutoFactory.h
choreolib/src/main/native/include/choreo/auto/TrajectoryCache.h
choreolib/src/main/native/include/choreo/trajectory/EventMarker.h
choreolib/src/main/native/include/choreo/trajectory/Trajectory.h

The split index was never passed to the load trajectory function.

[choreolib] Fix trajectory splitting for C++

---

choreolib/docs/Doxyfile
trajoptlib/docs/Doxyfile

The leading directory was being stripped.

[docs] Fix include paths in C++ API docs

---

docs/choreolib/auto-routines.md

The title for the second example listed here https://sleipnirgroup.github.io/Choreo/choreolib/auto-routines/ seems to be mistakenly 
> Creating an auto routine with **composition** and a monolithic trajectory 
which is the same title as the last, (don't do this), example. I believe this was instead meant to say
>  Creating an auto routine with **triggers** and a monolithic trajectory

Fix incorrect title of example in choreolib autoroutine docs

---

src/document/DocumentManager.ts

This matches the mechanism used for .traj files.

Chor autosave now triggers on serialized version, not undo stack size

---

mkdocs.yml

The docs have had the default mkdocs-material logo for a while. It looks like somebody tried to configure it to put the choreo logo in, but used the wrong config key. This adds the logo to the header.

Fix docs logo

---

choreolib/src/main/java/choreo/auto/AutoFactory.java
choreolib/src/main/java/choreo/auto/AutoRoutine.java
docs/choreolib/auto-factory.md
docs/choreolib/auto-routines.md

Currently, the way to construct AutoTrajectories is using the factory.trajectory method:
```
var trajectory = factory.trajectory("AmpToC1", routine);
```
This PR provides a better-named alternative:
```
var trajectory = routine.trajectory("AmpToC1");
```
Note: c++ and docs updates are still tbd.

Added routine.trajectory() method

---

choreolib/src/main/java/choreo/auto/AutoRoutine.java

Adds `AutoRoutine.observe(BooleanSupplier condition)`, which returns a `Trigger` bound to the routine's event loop. Naming is flexible.

[choreolib] Add AutoRoutine.observe()

---

choreolib/src/main/java/choreo/auto/AutoTrajectory.java
choreolib/src/main/java/choreo/util/AllianceFlipUtil.java
choreolib/src/test/java/choreo/auto/PoseFlippingTest.java

Renamed atPose() triggers as atTranslation(), added new atPose() that requires rotation tolerance as well.
Fixed logic in those triggers that sampled an alliance-dependent pose too early
Made the triggers and(active()).

Improve atPose clarity, routine-active safety, alliance-flipping safety

---

choreolib/build.gradle
choreolib/config.gradle

Normally, ChoreoLib CI targets WPILib development builds in PRs and WPILib releases in tagged releases. WPILib recently upgraded to Bookworm but hasn't made a release yet. This means PR builds must target Bookworm to pass, and release builds must target Bullseye to pass.
Pinning to a WPILib release makes us target Bullseye for all builds. This would make us incompatible with the libraries in the next WPILib release we're bundled in.
Pinning to a specific development build makes us target Bookworm for all builds. This fixes the compatibility issue but means our beta release won't be reproducible after WPILib does its yearly development artifact purge.
This PR pins to a WPILib development version since it's less problematic in the near term, and we don't expect needing to rebuild old beta …

[choreolib] Pin WPILib version to development build

---

choreolib/src/main/java/choreo/Choreo.java
choreolib/src/main/java/choreo/auto/AutoFactory.java
choreolib/src/main/java/choreo/auto/AutoTrajectory.java
choreolib/src/test/java/choreo/auto/AutoTestHelper.java

Enforces that routines or command compositions will not execute if odometry is not seeded (trajectory cannot be loaded, is empty, or alliance is unknown), and reduces complexity for the user.
See the [this message](https://discord.com/channels/975739302933856277/1013180308117536788/1315321921222742067) in Discord for context.
Usage:
```java
AutoFactory autoFactory = Choreo.createAutoFactory(
driveSubsystem::getPose,
driveSubsystem::resetOdometry, // Consumer<Pose2d>
driveSubsystem::followTrajectory
// ...
);
// Using AutoRoutine
AutoRoutine routine = autoFactory.newRoutine("example");
AutoTrajectory myTrajectory = routine.trajectory("myTrajectory");
routine.running().onTrue(myTrajectory.resetOdometry().andThen(myTrajectory.cmd()));
// Using command composition
Commands.sequence( …
```

[choreolib] Add AutoTrajectory.resetOdometry()

---

choreolib/src/main/java/choreo/Choreo.java
choreolib/src/main/java/choreo/auto/AutoFactory.java
choreolib/src/main/java/choreo/auto/AutoTrajectory.java
choreolib/src/test/java/choreo/auto/AutoTestHelper.java
docs/choreolib/auto-factory.md

Choreo.createAutoFactory() didn't do anything that the constructors couldn't already do.
Note: I still kept in a no-args createAutoFactory() method to give a proper deprecation notice to people who were using the choreolib betas, just in case of confusion.

[choreolib] Replace Choreo.createAutoFactory method with constructor

---

choreolib/src/main/java/choreo/auto/AutoRoutine.java
choreolib/src/main/java/choreo/auto/AutoTrajectory.java

Resolves #1010 
To save from extra dependency injection into `AutoRoutine` the implementation still exists as package private in `AutoTrajectory`. If that is not the desired solution I can make the necessary changes.

[choreolib-java] Move AutoTrajectory.resetOdometry() to AutoRoutine

---

.github/workflows/choreolib.yml

The update to NativeUtils 2025.9.0 (#991) seems to cause c++ builds for the RIO to be skipped on the 2024 docker container. Updating to the 2025 docker container fixes this issue and builds c++ rio artifacts again.

[ci] Update roboRIO docker container to 2025

---

docs/installation.md

Choreo is no longer bundled with WPILib and thus this line is no longer accurate.

Remove reference to Choreo being bundled with WPILib

---

.github/workflows/choreolib.yml
.github/workflows/docs.yml
.github/workflows/lint-format.yml
.github/workflows/release.yml
.github/workflows/trajoptlib-cpp.yml
.github/workflows/trajoptlib-rust.yml
.github/workflows/trajoptlib-sanitizers.yml

https://yossarian.net/til/post/actions-checkout-can-leak-github-credentials/
Fortunately everything we could have leaked gets revoked at the end of the workflow, but I think this credential issue might be messing with our release version number updating workflow.

Add github token and persist-credentials:false to all actions/checkout

---

docs/index.md

This makes it clearer that that link goes to the overall ChoreoLib docs and not just installation instructions.

[docs] Change homepage ChoreoLib card to not specify installation

---

src/document/DocumentModel.tsx
src/document/path/HolonomicPathStore.ts

This removes the need to use a group to keep this all in one undo step. It moves the logic to HolonomicPathStore and uses existing deserialization logic where possible.

Simplify logic when receiving a successful generation in UI

---

src/document/ExpressionStore.tsx

This was causing footguns worse than its convenience.

Remove numbers as valid input for dimensioned exprs

---

trajoptlib/include/trajopt/constraint/LinePointConstraint.hpp
trajoptlib/include/trajopt/constraint/PointLineConstraint.hpp
trajoptlib/include/trajopt/constraint/detail/LinePointSquaredDistance.hpp

LinePointDistance() was returning the squared norm, so squaring it again in the constraint was incorrect.

[trajoptlib] Fix keep-out polygon distance

---

src/components/config/variables/VariablesConfigPanel.tsx
src/document/ExpressionStore.tsx

These are redundant (since the name is right there) and blocked by the menu item click handler. There's also some issues with using function components directly inside Tooltips.

Remove dimension tooltips

---

src/document/DocumentManager.ts
src/document/ExpressionStore.tsx

I don't like having to do this, but we were already injecting this instance into every ExpressionStore through `Variables.createExpression`. (See former line 590 in ExpressionStore.tsx)
Unfortunately, undoing an operation that deletes an ExpressionStore (through deleting a waypoint, constraint, etc) does not use `createExpression`, so restored ExpressionStores did not get the injection. This worked in most cases because the Variables instance was injected two different ways, but only when the store was created after the Variables instance was created. In short, the existing system is fragile and puts annoying constraints on initialization order just to avoid a direct import as a way to access a global constant.

Directly depend on global variables store in expression stores

---

.vscode/settings.json

The STL has hundreds of these, which adds a lot of noise.

Remove file associations for STL headers

---

trajoptlib/src/DifferentialTrajectoryGenerator.cpp
trajoptlib/src/SwerveTrajectoryGenerator.cpp

Artificially constraining the step travel distance like this makes the solver report infeasible more often than it should. This isn't ideal in projects that don't even use keep-out constraints.
I saw differential drive generation report infeasible less often with the anti-tunneling constraint removed.
See #1108 for better potential alternatives.

[trajoptlib] Remove anti-tunneling constraint

---

choreolib/src/main/java/choreo/util/ChoreoAlert.java
docs/choreolib/getting-started.md

Docs have been updated to show that ChoreoAlerts exist(pretty important to get out before first complete release).
In addition, ChoreoAlert now runs a singular DriverStation.reportWarning the first time any alert gets triggered; acting as a reminder for people to check the alerts section if they do not have it up. It only prints once, so its designed for people who are still used to checking the console for errors.

Alert QoL + Docs updates

---

src/document/DocumentManager.ts

Missed this when adding `deleteAll()`

Clear path list when opening a new project

---

trajoptlib/src/DifferentialTrajectoryGenerator.cpp
trajoptlib/src/SwerveTrajectoryGenerator.cpp

Without it, the solver increases dt a lot, then reports infeasible on most paths.
The anti-tunneling constraint implicitly set an upper bound on dt, but setting an explicit upper bound is better.

[trajoptlib] Set dt upper bound

---

src/components/sidebar/PathSelector.tsx

Two issues:
1. when adding the icon that changes when generating and trajectory becoming stale, this started causing more re-renders of the whole path list row. I moved it to its own component that can re-render separately.
2. the path input now does not fire a rename unless the name has actually changed. Since people click on the path name and then click on the field, this was triggering renames that copied the file to the same path. These are now prevented.

Reduce pointless path renames when clicking in path selector

---

src/document/CommandStore.tsx
src/document/EventMarkerStore.tsx
src/document/path/HolonomicPathStore.ts

Because we deserialize the command payload recursively, it's not in the main document tree at that time, so we can't use mobx environment injection to access the CommandStore constructor.
Prior bug: Try to load a project with an event marker which has at least one command payload (i.e. not "None). Loading fails with a browser console warning about "Cannot get environment for CommandStore".

Avoid using environment when deserializing commands before tree attachment

---

src/components/config/robotconfig/PathGradient.tsx

The comments and GUI say higher accelerations should be green.

Fix linear acceleration gradient color

---

choreolib/src/main/java/choreo/util/ChoreoAlert.java
choreolib/src/main/java/choreo/util/ChoreoArrayUtil.java

Javadoc 21 complains about undocumented default constructors.

[choreolib] Fix JDK 21 Javadoc errors

---

src/document/ExpressionStore.tsx

We already expected `math.evaluate()` to return undefined in some cases. Previously we did try-catch blocks on `validate`, but this did not help when evaluating the variables which relied on other variables. Accessing a missing variable throws an exception in `math.evaluate()`.
Previously:
If you made a `variable2` referencing a `variable1`, even if the `variable2` wasn't referenced in any paths, deleting `variable1` would cause the app UI to white-out crash. This is because deleting or adding variables triggers re-evaluation on all expressions. `variable2` is re-evaluated and its value substituted into the scope. That re-evaluation had no try-catch, so the app crashed.
New behavior:
Upon deleting a variable, all direct (as previous) and transitive (new behavior) dependencies of that …

Expressions referencing missing variables now evaluate to undefined.

---

src/document/path/HolonomicPathStore.ts

This is an explicit update because updating on changes to the serialization doesn't catch all paths when first opening the project.

[ui] Update staleness indicator when deserializing paths

---

src/components/config/variables/PoseVariablesConfigPanel.tsx

Also, clicking on the (XXX m, XXX m, XXX rad) part also works as a dropdown button.
Also fixes that preview to use the `value` (last successful evaluation, which is what nearly everything else in the app uses), instead of re-evaluating and potentially getting `undefined`.

Move pose variable panel dropdown to right side to clarify purpose

---

choreolib/src/main/java/choreo/trajectory/Trajectory.java
choreolib/src/main/native/include/choreo/trajectory/Trajectory.h
trajoptlib/src/DifferentialTrajectoryGenerator.cpp
trajoptlib/src/SwerveTrajectoryGenerator.cpp

This can happen with two identical adjacent waypoints, where the heuristic determines there is 0 time between them. This should be acceptable, because the two waypoints often do not have incompatible constraints. However, averaging segment time over the `0` samples in the segment led to NaNs and a "nonfinite cost or constraints" (actually nonfinite decision variable) solver error.
Accompanying ChoreoLib changes handle a split trajectory with no samples, which was mistakenly thought to become possible with this change. The code is left in for safety's sake, since the case was not already handled.

[trajoptlib] [choreolib] Fix bugs preventing 0 samples between waypoints

---

.github/workflows/trajoptlib-sanitizers.yml

They're generally more reliable than GCC's.

[trajoptlib] Use LLVM sanitizers

---

docs/usage/editing-paths.md

The game name on the wiki is incorrectly stated as Charged Up when a Crescendo field is shown.

Fixed Incorrect game name

---

src-core/src/generation/heading.rs

```
[tav@myriad Choreo]$ cargo clippy
Checking choreo-core v2025.0.3 (/home/tav/git/Choreo/src-core)
error: redundant guard
--> src-core/src/generation/heading.rs:46:43
|
46 |             MaxAngularVelocity { max } if max == 0.0 => {
|                                           ^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_guards
note: the lint level is defined here
--> src-core/src/lib.rs:7:9
|
7  | #![deny(clippy::all)]
|         ^^^^^^^^^^^
= note: `#[deny(clippy::redundant_guards)]` implied by `#[deny(clippy::all)]`
help: try
|
46 -             MaxAngularVelocity { max } if max == 0.0 => {
46 +             MaxAngularVelocity { max: 0.0 } => {
|
error: could not compile `choreo-core` (lib) due to 1 previous error …
```

Fix redundant guard warning from clippy

---

src-tauri/src/logging.rs

```
error: this `repeat().take()` can be written more concisely
--> src-tauri/src/logging.rs:201:18
|
201 |         s.extend(std::iter::repeat(' ').take(width - s.len()));
|                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using `repeat_n()` instead: `std::iter::repeat_n(' ', width - s.len())`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_repeat_n
= note: `-D clippy::manual-repeat-n` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::manual_repeat_n)]`
error: this `repeat().take()` can be written more concisely
--> src-tauri/src/logging.rs:203:22
|
203 |         let spaces = std::iter::repeat(' ').take(width - s.len());
| …
```

Fix clippy warnings

---

.github/workflows/choreo.yml
.github/workflows/trajoptlib-cpp.yml
.github/workflows/trajoptlib-rust.yml
.github/workflows/trajoptlib-sanitizers.yml

Apparently you need 0.0.9 to utilize the new GHA caching endpoints.

[ci] Upgrade sccache action

---

trajoptlib/build.rs

This should have a more stable ABI than `/std:c++latest`, not that we intend our users to use precompiled versions of TrajoptLibRust anyway.

Use C++23 preview flag on Windows

---

Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/built.rs

In Windows CI, libgit2-sys takes 2m 9s to compile. It's not in the Cargo timing critical path though, so removing it didn't actually improve build times.

Remove libgit2 dependency from build info gathering
